--- !ditz.rubyforge.org,2008-03-06/project 
name: fnordlicht
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: fnordlicht/firmware
- !ditz.rubyforge.org,2008-03-06/component 
  name: fnordlicht/bootloader
- !ditz.rubyforge.org,2008-03-06/component 
  name: fnordlicht-controller/firmware
- !ditz.rubyforge.org,2008-03-06/component 
  name: fnordlicht-controller/bootloader
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2009-12-15 20:26:20.796707 Z
  log_events: 
  - - 2009-11-29 15:27:19.181082 Z
    - Alexander Neumann <alexander@bumpern.de>
    - created
    - ""
  - - 2009-12-15 20:26:20.796732 Z
    - Alexander Neumann <alexander@bumpern.de>
    - released
    - ""
